"use client";

import { FormEvent, useState } from "react";
import Button from "@/components/ui/Button";

export default function LeadForm() {
  const [submitted, setSubmitted] = useState(false);
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  return <form onSubmit={handleSubmit} className="rounded-xl border border-[#333538] bg-[#1a1c1f] p-5 sm:p-8"><h3 className="font-display text-2xl font-bold">Tell Us About Your Business</h3><p className="mt-2 text-sm text-[#c4c6cd]">A few practical details help frame the right conversation.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm text-[#c4c6cd]">Name<input required name="name" className="mt-2 w-full rounded-lg border border-[#282a2d] bg-[#0c0e11] px-4 py-3 text-[#f5f5f2] outline-none placeholder:text-[#6b7280] focus:border-[#ff6a00]" placeholder="Your name" /></label><label className="text-sm text-[#c4c6cd]">Work email<input required name="email" type="email" className="mt-2 w-full rounded-lg border border-[#282a2d] bg-[#0c0e11] px-4 py-3 text-[#f5f5f2] outline-none placeholder:text-[#6b7280] focus:border-[#ff6a00]" placeholder="name@company.com" /></label><label className="text-sm text-[#c4c6cd]">Company<input name="company" className="mt-2 w-full rounded-lg border border-[#282a2d] bg-[#0c0e11] px-4 py-3 text-[#f5f5f2] outline-none placeholder:text-[#6b7280] focus:border-[#ff6a00]" placeholder="Company name" /></label><label className="text-sm text-[#c4c6cd]">Primary channel<select name="channel" className="mt-2 w-full rounded-lg border border-[#282a2d] bg-[#0c0e11] px-4 py-3 text-[#f5f5f2] outline-none focus:border-[#ff6a00]"><option>Marketplace</option><option>D2C storefront</option><option>Paid media</option><option>Multi-channel operations</option></select></label></div><label className="mt-4 block text-sm text-[#c4c6cd]">What are you trying to solve?<textarea name="message" rows={4} className="mt-2 w-full resize-y rounded-lg border border-[#282a2d] bg-[#0c0e11] px-4 py-3 text-[#f5f5f2] outline-none placeholder:text-[#6b7280] focus:border-[#ff6a00]" placeholder="A little context about the product, channel, or operating challenge." /></label><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center"><Button type="submit" className="px-6 py-3">Request the Audit</Button>{submitted && <p role="status" className="text-sm text-emerald-400">Thank you. Your request has been captured for follow-up.</p>}</div></form>;
}
